/* AptFinder Dashboard — Application Logic */

(function () {
  "use strict";

  /* ── DATA ────────────────────────────────────────────────────── */
  var RAW_DATA = [{"Area": "Fairmount", "Building Name": "Broadridge", "Address": "1300 Fairmount Ave, Philadelphia, PA 19123", "Sub-Neighborhood": "Core Fairmount", "Management Company": "UDR (United Dominion Realty)", "Phone": "610-553-3384", "Email": "N/A (contact via UDR portal)", "Website": "https://www.udr.com/philadelphia-apartments/fairmount/broadridge/", "2BR Price Low": "$2,827", "2BR Price High": "$3,180", "Availability": "Multiple 2BR units available now through June", "Pool": "Yes", "Gym": "Yes", "Rooftop/Deck": "Yes (Skydeck lawn)", "Dog Park/Run": "Yes", "Concierge": "No", "Other Key Amenities": "ALDI on-site, podcast studio, movie theater, demo kitchen, yoga/spa, billiards", "Pet Rent (Monthly)": "$65/mo", "Pet Fee (One-Time)": "$300", "Breed Restrictions": "May apply (confirm)", "Weight Limit": "Not specified", "Year Built": "2021", "Total Units": "478", "Move-In Specials": "2 Months Free (move in by 3/16, 14-mo lease)", "Parking Type": "garage", "Parking Cost": "costs extra: $200/month unreserved, $250/month reserved ([UDR Expenses](https://www.udr.com/philadelphia-apartments/fairmount/broadridge/apartment-expenses))", "Reserved Parking": "yes, $250/month", "EV Charging": "yes, Level 2 ChargePoint stations on 2nd floor ([ChargeHub](https://chargehub.com/en/ev-charging-stations/united-states/pennsylvania/philadelphia/broadridge-philly/electric-car-stations-near-me?locId=132385))", "Parking Notes": "Third-party listing shows $175 unreserved/$199 reserved (possibly outdated) ([Black Label](https://blacklabelkw.com/properties/1300-fairmount-ave-flat-1bed-den-philadelphia-pa-19123-paph2032826)). Not included in rent. Prices subject to change."}];

  /* Placeholder - full app.js content */
}());